name: Publish release

on:
  workflow_call:
    inputs:
      commit-sha:
        description: 'The commit SHA that triggered the release.'
        required: true
        type: string

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Get release version
        id: get-version
        run: |
          MANIFEST_FILE="./custom_components/free_sleep/manifest.json"
          VERSION=$(jq --raw-output .version "$MANIFEST_FILE")
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Get release notes from commit
        id: release-notes
        env:
          COMMIT_SHA: ${{ inputs.commit-sha }}
        run: |
          RELEASE_NOTES=$(git log -1 --pretty=format:%b "$COMMIT_SHA")
          echo "release-notes=$RELEASE_NOTES" >> "$GITHUB_OUTPUT"

      - name: Create tag and release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get-version.outputs.version }}
          RELEASE_NOTES: ${{ steps.release-notes.outputs.release-notes }}
        run: |
          git config user.name "hass-free-sleep[bot]"
          git config user.email "245959007+hass-free-sleep[bot]@users.noreply.github.com"
          git tag -a "v$VERSION" -F - <<< "$RELEASE_NOTES"
          git push origin "v$VERSION"
          gh release create "v$VERSION" --title "$VERSION" --verify-tag --notes-from-tag "v$VERSION"
